

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leetscope?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema-mysql.sql
      data-locations: classpath:database/schema-data.sql

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

server:
  tomcat:
    max-http-form-post-size: 20MB
  port: 8080