spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leetscope?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  sql:
    init:
      schema-locations: classpath:database/schema-mysql.sql

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true